### ISSUE TITLE
java.lang.LinkageError: loader constraint violation: when resolving field "preMixinAsmClassTransformer"

### ISSUE THREAD

**Issue by florensie** [Devan-Kerman/GrossFabricHacks#9]
Can be reproduced with something like this:
```java
public class EarlyInit implements PrePreLaunch {
    @Override
    public void onPrePreLaunch() {
        TransformerApi.registerPreMixinAsmClassTransformer((name, node) -> {
			
        });
    }
}
```
https://pastebin.com/j5ckYgAw
```
[18:14:50] [main/ERROR]: Error loading companion plugin class [net.devtech.grossfabrichacks.mixin.GrossFabricHacksPlugin] for mixin config [grossfabrichacks.mixins.json]. The plugin may be out of date: LinkageError:loader constraint violation: when resolving field "preMixinAsmClassTransformer" the class loader (instance of net/fabricmc/loader/launch/knot/UnsafeKnotClassLoader) of the referring class, org/spongepowered/asm/mixin/transformer/HackedMixinTransformer, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the field's resolved type, net/devtech/grossfabrichacks/transformer/asm/AsmClassTransformer, have different Class objects for that type
java.lang.LinkageError: loader constraint violation: when resolving field "preMixinAsmClassTransformer" the class loader (instance of net/fabricmc/loader/launch/knot/UnsafeKnotClassLoader) of the referring class, org/spongepowered/asm/mixin/transformer/HackedMixinTransformer, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the field's resolved type, net/devtech/grossfabrichacks/transformer/asm/AsmClassTransformer, have different Class objects for that type
	at net.devtech.grossfabrichacks.transformer.TransformerApi.registerPreMixinAsmClassTransformer(TransformerApi.java:37) ~[grossfabrichacks-6.1.jar:?]
	at be.florens.cursedcraft.EarlyInit.onPrePreLaunch(EarlyInit.java:18) ~[cursedcraft.main/:?]
	at net.devtech.grossfabrichacks.mixin.GrossFabricHacksPlugin.<clinit>(GrossFabricHacksPlugin.java:45) ~[grossfabrichacks-6.1.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:83) ~[fabric-loader-0.10.8.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:598) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:475) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:437) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.10.8.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.UnsafeKnotClassLoader.loadClass(UnsafeKnotClassLoader.java:67) [grossfabrichacks-6.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:222) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by SilverAndro** [comment]
Seems to be an issue with 6.1, downgrading to 4.5 worked for me

**Comment by florensie** [comment]
I guess that somewhat pinpoints the issue.
Also what kind of versioning system goes from 4.5 to 6.1 lol.
